### ISSUE TITLE
Sort out these branches

### ISSUE THREAD

**Issue by u8sand** [MaayanLab/scAVI#63]
@jeevangelista what branch are you using, can we sort out which is the true latest and clean up some branches. It's a bit confusing.

**Comment by u8sand** [comment]
- [ ] `scv0` to be renamed to `mcf10a` because that's what it is

**Comment by u8sand** [comment]
@AviMaayan can someone modify the settings of this repository, make the `default branch` `master`

**Comment by jeevangelista** [comment]
are we renaming scv or merging it to master?

**Comment by u8sand** [comment]
@jeevangelista I've renamed it already just waiting for master to become the primary branch before removing scv

**Comment by AviMaayan** [comment]
I think I just did it. Credit to @sherry-jenkins that showed me how to do it.
